### ISSUE TITLE
[1.12.2] Beds Stop Working

### ISSUE THREAD

**Issue by NielsPilgaard** [Mordenkainen/BedPatch#1]
Hey!

I'm not certain this bug is actually caused by BedPatch, but it's the most likely culprit.

Beds randomly stop functioning on servers - You can lie in them, but it doesn't skip the night, ever.
It doesn't appear to have a trigger, and it solves itself after a random amount of time, without restarting the server.

Would a forced crash log help tracking the issue down?

**Comment by Mordenkainen** [comment]
A crash log would probably not help in this case.

All players are in beds, but it doesn't skip night? Hmmmm.

I don't think it's likely that it's BedPatch, as it doesn't actually touch anything to do with that, but I'll take a look.

**Comment by NielsPilgaard** [comment]
Thank you :)

We're using the server sleep system from Quark (like Morpheus), so I'll make an issue on Quark's tracker aswell, but it can happen when there's only 1 on the server, so I'm guessing that's not it.

**Comment by Mordenkainen** [comment]
I have found a better way to implement a fix for the bed issue. I should have an updated Bed Patch posted sometime tomorrow. Once it is up, try loading it and see if it resolves the issue.

**Comment by NielsPilgaard** [comment]
Sounds good, thank you!

**Comment by Mordenkainen** [comment]
The new version is up. Give it a spin and let me know if your issue is resolved!

**Comment by Mordenkainen** [comment]
Ok, I'm closing this issue. Seems like this is caused by a problem in Quark.

**Comment by NielsPilgaard** [comment]
Yeah. Thanks for your help!
