### ISSUE TITLE
Crash when trying to eat anything

### ISSUE THREAD

**Issue by ghost** [Mordenkainen/BedPatch#2]
Mod: bedpatch-2.0-1.12.2
Forge: 1.12.2-forge1.12.2-14.23.2.2611
Optifine: OptiFine_1.12.2_HD_U_C8
Foamfix: foamfix-0.8.1-1.12-anarchy

Steps to reproduce:
1- Right click with any food in hand.
2- Profit.

[Crash log](https://pastebin.com/rxAFgbE6)

Although there's nothing in the crash log pointing to this mod (which made it quite hard to track) the crash only happens when this mod is active.

**Comment by Mordenkainen** [comment]
This is something added by AppleCore. I don't see any indication either in AppleCore or Bed Patch where they would conflict.

Searching for crashes related to "java.lang.NoSuchFieldError: itemInUseMaxDuration" I find several, all on MC instances containing AppleCore, and none of these had Bed Patch.

I'll leave this open for the time being, but the log seems to point at AppleCore as the mod that failed.

**Comment by Jizanthapus** [comment]
I have this crash as well. It seems to be related to Bed Patch 2.0. I don't see a crash with 1.0.

[Crash log](https://gist.github.com/Jizanthapus/b4d8579a450857eb11d6158005f0e763)

**Comment by Mordenkainen** [comment]
Please pastebin your entire forge log.

**Comment by Jizanthapus** [comment]
[fml-client-latest](https://pastebin.com/3Db3CNAW)

[fml-junk-earlystartup](https://pastebin.com/ySCFHNS5)

[latest](https://pastebin.com/hB4XbNrH)

**Comment by Mordenkainen** [comment]
Ok, looks like there is some collision with the patches AppleCore is applying. No idea why since they don't touch the same classes.

I think I have a workaround, but will need to do a little testing before I post it.

**Comment by Mordenkainen** [comment]
This should be fixed with the 2.1 version!
