### ISSUE TITLE
bedpatch v2.1 (1.12.2) preventing sponge from loading

### ISSUE THREAD

**Issue by colinrgodsey** [Mordenkainen/BedPatch#3]
Early reference error. Early mod classloading of NMS classes is causing sponge mixin to fail. 

Logs:

https://gist.github.com/colinrgodsey/aa77126abbc49f46157e798700f3bea2

**Comment by Mordenkainen** [comment]
Unless the Sponge team can provide info on how to fix that, the fix would need to be on the Sponge side.

The mod is a standard Forge CoreMod, and loads very late in the cycle (SortingIndex of 1200). If Sponge hasn't gotten in there to make it's patches yet, there isn't much I can do from my side. Looking at the Sponge code they do not appear to supply a SortingIndex for their CoreMod... I think this means they are likely to always patch last, which is probably the source of the issue.

**Comment by colinrgodsey** [comment]
it doesn't appear to be a patching order issue- it looks like you inadvertently reference EntityPlayer before the FML patching phase is complete. I believe I fixed it, submitting a PR now.
